Repository jaja-x/mod_wikisearch, pull requests merged in 2021-11, with the labels that each got.

#1 Fix codding styles
  README.md
  index.php
  lang/en/wikisearch.php
  locallib.php
  view.php
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#5 Update readme
  README.md
  mod_form.php
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#6 Feature toggler
  amd/src/wikisearch.js
  view.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 Update project version
  version.php
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#8 Add new Georgian language support
  lang/ka/wikisearch.php
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, translation
